import { IMongoDbPluginOptions, MongoDbPlugin, MongoDbRecord } from "@agrejus/db-framework-plugin-mongodb";
import { s, InferType, SchemaTypes, DataContext } from "@agrejus/db-framework";

export enum Tables {
    Sample = "api_keys"
}

enum TestEnum {
    test = "test",
    test2 = "test2",

}

const SampleSchema = s.define(Tables.Sample, {
    id: s.string({ isId: true }),
    timestamp: s.number({ isAutoGenerated: true }),
    key: s.string(),
    is_valid: s.boolean(),
    created_at: s.number({ isAutoGenerated: true }),
    updated_at: s.number({ isAutoGenerated: true })
});

type Sample = InferType<typeof SampleSchema>;

class MyContext extends DataContext<Tables, MongoDbRecord<Tables>, "id" | "timestamp", IMongoDbPluginOptions, MongoDbPlugin<Tables, MongoDbRecord<Tables>, IMongoDbPluginOptions>> {

    contextId() {
        return MyContext.name;
    }

    constructor() {
        super({ dbName: "moso", connectionString: "mongodb://root:HBhKP4YVVc@127.0.0.1:27017" }, MongoDbPlugin, { performance: { enabled: true } })
    }

    samples = this.dbset().default<Sample>(SampleSchema).exclude("created_at", "updated_at").create();
}

const context = new MyContext();

const fn = async () => {
    debugger;
    // const found = await context.samples.find(w => w.reward_id == 12);


    // const x = await context.samples.get('568e5e48-b704-47fc-9f48-99026b9ba2b0');

    // console.log(x);
    await context.samples.add({
        is_valid: true,
        key: "MOSO-Test"
    })
    const response = await context.saveChanges();

    console.log(response);

    // if (found != null) {
    //     found.reward_id = 1;
    //     await context.saveChanges();
    // } 


    const all = await context.samples.all();

    console.log(all)
    debugger;
}

fn();